// Code generated by entc, DO NOT EDIT.

package execlog

const (
	// Label holds the string label denoting the execlog type in the database.
	Label = "exec_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTimestamp holds the string denoting the timestamp field in the database.
	FieldTimestamp = "timestamp"
	// FieldLog holds the string denoting the log field in the database.
	FieldLog = "log"
	// FieldErrmsg holds the string denoting the errmsg field in the database.
	FieldErrmsg = "errmsg"
	// FieldErrValues holds the string denoting the err_values field in the database.
	FieldErrValues = "err_values"
	// FieldStackTrace holds the string denoting the stack_trace field in the database.
	FieldStackTrace = "stack_trace"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// Table holds the table name of the execlog in the database.
	Table = "exec_logs"
)

// Columns holds all SQL columns for execlog fields.
var Columns = []string{
	FieldID,
	FieldTimestamp,
	FieldLog,
	FieldErrmsg,
	FieldErrValues,
	FieldStackTrace,
	FieldStatus,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "exec_logs"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"action_log_exec_logs",
	"task_log_exec_logs",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
