// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ActionLogsColumns holds the columns for the "action_logs" table.
	ActionLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "started_at", Type: field.TypeInt64},
		{Name: "stopped_at", Type: field.TypeInt64, Nullable: true},
		{Name: "log", Type: field.TypeString, Nullable: true},
		{Name: "errmsg", Type: field.TypeString, Nullable: true},
		{Name: "err_values", Type: field.TypeJSON, Nullable: true},
		{Name: "stack_trace", Type: field.TypeJSON, Nullable: true},
		{Name: "status", Type: field.TypeString},
		{Name: "job_action_logs", Type: field.TypeInt, Nullable: true},
	}
	// ActionLogsTable holds the schema information for the "action_logs" table.
	ActionLogsTable = &schema.Table{
		Name:       "action_logs",
		Columns:    ActionLogsColumns,
		PrimaryKey: []*schema.Column{ActionLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "action_logs_jobs_action_logs",
				Columns:    []*schema.Column{ActionLogsColumns[9]},
				RefColumns: []*schema.Column{JobsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// AlertsColumns holds the columns for the "alerts" table.
	AlertsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "title", Type: field.TypeString, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "detector", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "new"},
		{Name: "severity", Type: field.TypeString, Nullable: true},
		{Name: "detected_at", Type: field.TypeInt64, Nullable: true},
		{Name: "created_at", Type: field.TypeInt64},
		{Name: "closed_at", Type: field.TypeInt64, Nullable: true},
	}
	// AlertsTable holds the schema information for the "alerts" table.
	AlertsTable = &schema.Table{
		Name:       "alerts",
		Columns:    AlertsColumns,
		PrimaryKey: []*schema.Column{AlertsColumns[0]},
	}
	// AnnotationsColumns holds the columns for the "annotations" table.
	AnnotationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "timestamp", Type: field.TypeInt64},
		{Name: "source", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "value", Type: field.TypeString},
		{Name: "attribute_annotations", Type: field.TypeInt, Nullable: true},
	}
	// AnnotationsTable holds the schema information for the "annotations" table.
	AnnotationsTable = &schema.Table{
		Name:       "annotations",
		Columns:    AnnotationsColumns,
		PrimaryKey: []*schema.Column{AnnotationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "annotations_attributes_annotations",
				Columns:    []*schema.Column{AnnotationsColumns[5]},
				RefColumns: []*schema.Column{AttributesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// AttributesColumns holds the columns for the "attributes" table.
	AttributesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "key", Type: field.TypeString},
		{Name: "value", Type: field.TypeString},
		{Name: "type", Type: field.TypeString},
		{Name: "context", Type: field.TypeJSON},
		{Name: "alert_attributes", Type: field.TypeString, Nullable: true},
	}
	// AttributesTable holds the schema information for the "attributes" table.
	AttributesTable = &schema.Table{
		Name:       "attributes",
		Columns:    AttributesColumns,
		PrimaryKey: []*schema.Column{AttributesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "attributes_alerts_attributes",
				Columns:    []*schema.Column{AttributesColumns[5]},
				RefColumns: []*schema.Column{AlertsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// JobsColumns holds the columns for the "jobs" table.
	JobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "step", Type: field.TypeInt64},
		{Name: "input", Type: field.TypeJSON},
		{Name: "alert_jobs", Type: field.TypeString, Nullable: true},
	}
	// JobsTable holds the schema information for the "jobs" table.
	JobsTable = &schema.Table{
		Name:       "jobs",
		Columns:    JobsColumns,
		PrimaryKey: []*schema.Column{JobsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "jobs_alerts_jobs",
				Columns:    []*schema.Column{JobsColumns[4]},
				RefColumns: []*schema.Column{AlertsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ReferencesColumns holds the columns for the "references" table.
	ReferencesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "source", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "url", Type: field.TypeString},
		{Name: "comment", Type: field.TypeString, Nullable: true},
		{Name: "alert_references", Type: field.TypeString, Nullable: true},
	}
	// ReferencesTable holds the schema information for the "references" table.
	ReferencesTable = &schema.Table{
		Name:       "references",
		Columns:    ReferencesColumns,
		PrimaryKey: []*schema.Column{ReferencesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "references_alerts_references",
				Columns:    []*schema.Column{ReferencesColumns[5]},
				RefColumns: []*schema.Column{AlertsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ActionLogsTable,
		AlertsTable,
		AnnotationsTable,
		AttributesTable,
		JobsTable,
		ReferencesTable,
	}
)

func init() {
	ActionLogsTable.ForeignKeys[0].RefTable = JobsTable
	AnnotationsTable.ForeignKeys[0].RefTable = AttributesTable
	AttributesTable.ForeignKeys[0].RefTable = AlertsTable
	JobsTable.ForeignKeys[0].RefTable = AlertsTable
	ReferencesTable.ForeignKeys[0].RefTable = AlertsTable
}
