// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Alert is the predicate function for alert builders.
type Alert func(*sql.Selector)

// Attribute is the predicate function for attribute builders.
type Attribute func(*sql.Selector)

// Finding is the predicate function for finding builders.
type Finding func(*sql.Selector)
